import {expect,it} from 'vitest';
import {readFileSync} from 'node:fs';
import {scorePRCS} from '../worker/prcs';
// Generated by the unchanged package Python reference (21 canonical + full/partial/zero).
const fixtures=JSON.parse(readFileSync('tests/fixtures/prcs-reference.json','utf8'));
function compare(a:any,b:any,path='result'){
 if(typeof b==='number'){expect(Math.abs(a-b),path).toBeLessThan(1e-10);return;}
 if(b&&typeof b==='object'){expect(Object.keys(a).sort(),path).toEqual(Object.keys(b).sort());for(const k of Object.keys(b))compare(a[k],b[k],path+'.'+k);return;}
 expect(a,path).toEqual(b);
}
for(const f of fixtures)it('Python parity: '+f.name,()=>{
 const actual=scorePRCS(f.answers,f.exact);
 if(actual.status!=='INSUFFICIENT_SIGNAL'&&actual.one_notch_flip_radius.items){
  const items=actual.one_notch_flip_radius.items,expected=f.result.one_notch_flip_radius.items;
  // NumPy BLAS and JS can order symmetric, equal-gain witnesses differently at
  // machine precision. Require the same edit count, competitor and per-edit gain.
  expect(new Set(items).size).toBe(items.length);
  items.forEach((id,i)=>expect(f.notch_gains[id]).toBeCloseTo(f.notch_gains[expected[i]],12));
  actual.one_notch_flip_radius.items=expected;
 }
 compare(actual,f.result);
});
