import { MODEL_VERSION, SCHEMA_VERSION, APP_VERSION, validateAnswers } from './scoring';
export type Draft={modelVersion:string;answers:(number|null)[];index:number;startedAt:string};
export type Attempt={attemptId:string;participantId:string;feedbackToken:string;schemaVersion:number;modelVersion:string;answers:number[];startedAt:string;completedAt:string;durationMs:number;imported:boolean;appVersion:string;saved:boolean};
export function read<T>(key:string):T|null{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}}
export function write(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
export function freshDraft():Draft{return {modelVersion:MODEL_VERSION,answers:Array(80).fill(null),index:0,startedAt:new Date().toISOString()};}
export function loadDraft():Draft{const d=read<Draft>('starseed2-draft');if(d&&d.modelVersion===MODEL_VERSION&&Array.isArray(d.answers)&&d.answers.length===80&&Array.from(d.answers).every(v=>v===null||(Number.isInteger(v)&&v>=-3&&v<=3))&&Number.isInteger(d.index)&&d.index>=0&&d.index<80&&Number.isFinite(Date.parse(d.startedAt)))return d;return freshDraft();}
export function loadAttempt():Attempt|null{const a=read<Attempt>('starseed2-attempt');try{if(!a||a.modelVersion!==MODEL_VERSION)return null;validateAnswers(a.answers);return a;}catch{return null;}}
export function participant(){let p=read<string>('starseed2-participant');if(!p||!/^[0-9a-f-]{36}$/i.test(p)){p=crypto.randomUUID();write('starseed2-participant',p);}return p;}
export function newAttempt(answers:number[],startedAt:string,imported:boolean):Attempt{validateAnswers(answers);const completedAt=new Date().toISOString();return {attemptId:crypto.randomUUID(),participantId:participant(),feedbackToken:crypto.randomUUID(),schemaVersion:SCHEMA_VERSION,modelVersion:MODEL_VERSION,answers:[...answers],startedAt,completedAt,durationMs:Math.max(0,Date.parse(completedAt)-Date.parse(startedAt)),imported,appVersion:APP_VERSION,saved:false};}
export async function submitAttempt(a:Attempt){const response=await fetch('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(a)});const data=await response.json() as {error?:string;result:ReturnType<typeof import("./scoring").scoreAnswers>};if(!response.ok)throw new Error(data.error||'暫時無法儲存，請稍後再試。');return data;}
