import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {Link,useParams,useLocation} from 'react-router-dom';
import Markdown from 'react-markdown';
import {ArrowUpRight,ArrowRight,ChevronLeft,Check,Copy,Orbit,RefreshCw,ChevronDown,Menu as MenuIcon} from 'lucide-react';
import civs from '../data/civilizations.json';
import resultCopy from '../../starseed_strict180_web_handoff_v4_1_min/result_copy.zh-Hant.json';
import demoFixture from '../data/demo-responses.json';
import {categories,Icon,ExportButton} from '../App';
import {MODEL_VERSION,questions,makeExport,parseImport,type Responses,type Answer,type Question} from '../shared/questionnaire';
import type {ScoringResult} from '../shared/result';
import {participant,write,submitAttempt,type Attempt} from '../shared/session';
import PairComparison from './PairComparison';
const fmt=(n:number,digits=2)=>n.toFixed(digits);
const civilization=(id:string)=>civs.find(c=>c.lineageId===id)!;
const shortCopy=(id:string)=>resultCopy.lineages[id as keyof typeof resultCopy.lineages]?.short;
const encodeResponses=(responses:Responses)=>btoa(JSON.stringify(makeExport(responses))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function readShared(search:string):{shared:boolean;responses?:Responses;error?:string}{
 const legacy=new URLSearchParams(search).has('s'),raw=new URLSearchParams(search).get('s2');
 if(!legacy&&!raw)return {shared:false};
 if(legacy)return {shared:true,error:'這份分享連結屬於舊版測驗，無法轉換為新版結果。請向分享者索取新版連結，或重新完成 60 題測驗。'};
 try{if(raw!.length>16000)throw Error();const payload=JSON.parse(atob(raw!.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-raw!.length%4)%4)));return {shared:true,responses:parseImport(payload)};}
 catch{return {shared:true,error:'這份分享連結的答案不完整或屬於不同測驗版本。請向分享者索取新版連結。'};}
}
function validResult(value:ScoringResult|undefined):value is ScoringResult{
 try{
  if(!value||value.diagnostic.model_version!==MODEL_VERSION)return false;
  if(value.public.status==='no_classification')return value.diagnostic.status==='zero_information';
  if(value.public.status!=='classified'||value.diagnostic.status!=='classified')return false;
  const p=value.public,d=value.diagnostic;
  return Boolean(civilization(p.primary.id)&&civilization(p.runner_up.id)&&d.ranking.length===21&&d.item_contributions.length===questions.length&&civs.every(c=>Number.isFinite(p.scores[c.lineageId])&&d.ranking.some(row=>row.id===c.lineageId))&&Number.isFinite(p.stability.index)&&p.stability.label in stabilityLabels&&d.classification_stability.components&&d.winner_runner_pair_stability.model_pair_margin_t_points&&d.winner_runner_pair_stability.family_pair_margin_t_points);
 }catch{return false;}
}
async function requestScore(responses:Responses,signal?:AbortSignal):Promise<ScoringResult>{const response=await fetch('/api/score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({responses}),signal});const data=await response.json() as {modelVersion?:string;result?:ScoringResult;error?:string};if(!response.ok)throw Error(data.error||'暫時無法計算報告，請重試。');if(data.modelVersion!==MODEL_VERSION||!validResult(data.result))throw Error('報告版本與目前測驗不相容，請重新載入頁面。');return data.result;}
function useTitle(title:string){useEffect(()=>{document.title=`${title}｜21 文明星種測驗`;},[title]);}
export function Atlas(){useTitle('文明圖鑑');return <div className="atlas-page section"><h1>你所熟悉的星光，<br/><em>也在尋找你。</em></h1><p className="page-intro">從文明的誕生，到靈魂在地球的使命。走進每一個星際世界的完整記憶。</p>{categories.map(cat=><section className="category-block" key={cat.name} style={{'--category':cat.color} as React.CSSProperties}><div className="category-heading"><h2>{cat.name}</h2></div><div className="civ-grid">{civs.filter(c=>c.category===cat.name).map(c=><Link to={`/civilizations/${c.id}`} className="civ-card" key={c.id}><div className="civ-card-art"><Icon id={c.id}/><span className="civ-index">{String(civs.findIndex(item=>item.id===c.id)+1).padStart(2,'0')}</span><ArrowUpRight className="civ-arrow" size={22}/></div><span className="english">{c.english}</span><h3>{c.name}</h3><p>{c.subtitle.replace(/^#+\s*/, '')}</p></Link>)}</div></section>)}</div>;}
export function OfficialText({id}:{id:number}){
 const [text,setText]=useState(''),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{const abort=new AbortController();setText('');setError(false);fetch(`/texts/${id}.md`,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.text();}).then(setText).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>abort.abort();},[id,retry]);
 const chapters=useMemo(()=>text.split('\n').map((line,i)=>({line:i+1,title:line.replace(/^#+\s*/,'').replace(/\*\*/g,'')})).filter((_,i)=>/^#{1,3}\s/.test(text.split('\n')[i])),[text]);
 if(error)return <div className="panel"><p>文明檔案暫時未能載入。</p><button className="button" onClick={()=>setRetry(retry+1)}>重新載入完整文案</button></div>;
 if(!text)return <div className="loading" role="status"><Orbit/> 正在展開文明檔案……</div>;
 const Heading=({node,children}:any)=><h2 id={`chapter-${node?.position?.start.line}`}>{children}</h2>;
 return <section className="official-layout" id="official"><aside className="reading-toc"><p className="eyebrow">完整文明檔案</p><h3>沿著記憶閱讀</h3><details open={window.innerWidth>=1000||undefined}><summary>章節導覽 <ChevronDown size={16}/></summary><nav aria-label="文明章節">{chapters.map((c,i)=><a href={`#chapter-${c.line}`} key={c.line}><span>{String(i+1).padStart(2,'0')}</span>{c.title}</a>)}</nav></details><span className="reading-note">官方正文 · 完整收錄</span></aside><article className="official-prose"><Markdown components={{h1:Heading,h2:Heading,h3:Heading}}>{text}</Markdown><div className="reading-end"><span>✦</span><p>這段星際記憶，已完整展開。</p><a href="#main">返回頁首 ↑</a></div></article></section>;
}
export function Civilization(){const {id}=useParams();const c=civs.find(c=>String(c.id)===id);useTitle(c?`${c.name}文明`:'找不到文明');if(!c)return <div className="empty"><h1>找不到這個文明。</h1><Link to="/civilizations">返回文明圖鑑</Link></div>;return <><div className="civilization-page section"><Link className="text-button" to="/civilizations"><ChevronLeft size={17}/> 返回文明圖鑑</Link><section className="civilization-hero"><div><p className="eyebrow">文明檔案 {String(civs.findIndex(item=>item.id===c.id)+1).padStart(2,'0')} / 21 <span className="category-tag">{c.category}</span></p><p className="english">{c.english}</p><h1>{c.name}</h1><p className="civ-subtitle">{c.subtitle}</p><a className="text-button" href="#official">展開完整文明記憶 ↓</a></div><Icon id={c.id}/></section><OfficialText id={c.id}/><section className="related"><div className="section-heading"><h2>繼續穿越星海</h2><Link className="text-button" to="/quiz">尋找我的起源 <ArrowUpRight size={16}/></Link></div><div className="related-grid">{civs.filter(x=>x.category===c.category&&x.id!==c.id).map(x=><Link key={x.id} to={`/civilizations/${x.id}`}><Icon id={x.id} size="small"/><span>{x.name}<small>{x.category}</small></span><ArrowUpRight size={17}/></Link>)}</div></section></div></>;}
export function Report({attempt,demo=false,onSaved,onEdit,onRestart}:{attempt?:Attempt|null;demo?:boolean;onSaved?:(a:Attempt)=>void;onEdit?:()=>void;onRestart:()=>void}){
 const location=useLocation(),shared=useMemo(()=>readShared(location.search),[location.search]);
 const responses=shared.shared?shared.responses:demo?demoFixture.responses as Responses:attempt?.responses;
 const localAttempt=!demo&&!shared.shared?attempt:null;
 const responseKey=JSON.stringify(responses),sourceKey=`${shared.shared?'shared':demo?'demo':localAttempt?.attemptId}:${responseKey}`;
 const [loaded,setLoaded]=useState<{key:string;result:ScoringResult}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[saveState,setSaveState]=useState(''),[saving,setSaving]=useState(false);
 const onSavedRef=useRef(onSaved);onSavedRef.current=onSaved;
 const result=loaded?.key===sourceKey?loaded.result:null;
 const [identityChoice,setIdentityChoice]=useState<string|null>(()=>demo||(localStorage.getItem('starseed2-identity-seen')==='1'&&localStorage.getItem('starseed2-familiarity'))?'skipped':null);
 const [scrollMode,setScrollMode]=useState<'top'|'down'|'up'>('top');
 useEffect(()=>{let last=window.scrollY;const onScroll=()=>{const y=window.scrollY;setScrollMode(y<20?'top':y<last?'up':'down');last=y;};window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll);},[]);
 useEffect(()=>{
  if(!responses)return;let active=true;const abort=new AbortController();setError('');setSaveState('');setSaving(false);
  async function load(){
   try{let next:ScoringResult;
    if(localAttempt?.saved&&validResult(localAttempt.result))next=localAttempt.result;
    else if(localAttempt&&!localAttempt.saved){
     setSaving(true);
     try{const saved=await submitAttempt(localAttempt);if(!validResult(saved.result))throw Error('報告版本不相容，請重新載入頁面。');next=saved.result;if(active){onSavedRef.current?.({...localAttempt,saved:true,result:next});setSaveState('匿名校準資料已儲存。');}}
     catch(e){if(!active)return;setSaveState((e as Error).message);next=validResult(localAttempt.result)?localAttempt.result:await requestScore(responses!,abort.signal);if(active)onSavedRef.current?.({...localAttempt,result:next});}
    }else next=await requestScore(responses!,abort.signal);
    if(active)setLoaded({key:sourceKey,result:next});
   }catch(e){if(active)setError((e as Error).message);}finally{if(active)setSaving(false);}
  }
  void load();return()=>{active=false;abort.abort();};
 },[sourceKey,retry]);
 useTitle(demo?'報告範例':result?.public.status==='classified'?`${civilization(result.public.primary.id).name}・你的星際報告`:'你的星際報告');
 async function save(){if(!localAttempt||saving)return;setSaving(true);setSaveState('正在匿名儲存完成的答案……');try{const response=await submitAttempt(localAttempt);if(!validResult(response.result))throw Error('報告版本不相容，請重新載入頁面。');onSaved?.({...localAttempt,saved:true,result:response.result});setLoaded({key:sourceKey,result:response.result});setSaveState('匿名校準資料已儲存。');}catch(e){setSaveState((e as Error).message);}finally{setSaving(false);}}
 if(shared.error)return <div className="empty"><Orbit size={40}/><h1>這份分享需要更新。</h1><p>{shared.error}</p><Link className="button gold" to="/quiz">開始新版測驗 <ArrowUpRight size={18}/></Link></div>;
 if(!responses)return <div className="empty"><Orbit size={40}/><h1>你的星際報告，等待開啟。</h1><p>完成 60 道提問，或從選單匯入你的答案。</p><Link className="button gold" to="/quiz">開始測驗 <ArrowUpRight size={18}/></Link><Link to="/sample" className="text-button">查看報告範例</Link></div>;
 if(error)return <div className="empty"><Orbit size={40}/><h1>報告暫時未能開啟。</h1><p role="alert">{error}</p><button className="button gold" onClick={()=>setRetry(n=>n+1)}>重新載入報告 <RefreshCw size={18}/></button><ExportButton responses={responses}/></div>;
 if(!result)return <div className="empty" role="status"><Orbit className="report-loading-orbit" size={40}/><h1>正在整理你的星際座標。</h1><p>正在計算 21 個文明的分數、比較結果與結構穩定度……</p></div>;
 if(result.public.status==='no_classification'||result.diagnostic.status!=='classified')return <div className="empty zero"><Orbit size={50}/><p className="eyebrow">方向尚未形成</p><h1>你的答案，<br/>暫未形成可判讀方向。</h1><p>本次答案在模型中沒有足夠的方向資訊，因此不指定 Primary。你可以回顧答案，再開啟報告。</p>{localAttempt&&<button className="button gold" onClick={onEdit}>回去修改答案 <ArrowRight size={18}/></button>}<ExportButton responses={responses}/>{saveState&&<small role="status">{saveState}</small>}{localAttempt&&!localAttempt.saved&&<button onClick={save} disabled={saving} className="text-button">重新儲存匿名答案</button>}</div>;
 if(!demo&&!shared.shared&&identityChoice===null)return <IdentityGate onContinue={value=>{localStorage.setItem('starseed2-identity-seen','1');localStorage.setItem('starseed2-familiarity',value.familiarity);setIdentityChoice(value.identity)}}/>;
 const classified={public:result.public,diagnostic:result.diagnostic},c=civilization(result.public.primary.id);
 return <div className="report-page section">{demo&&<div className="demo-banner"><span>報告範例</span> 使用固定範例答案展示；不會保存至匿名校準資料庫。<Link to="/quiz">開始我的測驗 <ArrowUpRight size={15}/></Link></div>}{shared.shared&&<div className="demo-banner"><span>分享報告</span>這是分享連結中的答案結果。</div>}<div className={`result-floating ${scrollMode==='down'?'is-visible':''}`}><span>你的星際報告</span><ShareButton responses={responses} civilization={c.name}/></div><div className={`result-scroll-header ${scrollMode==='up'?'is-visible':''}`}><Link to="/" aria-label="回到首頁"><Orbit size={19}/><span>星際起源</span></Link><Link to="/civilizations" aria-label="探索文明圖鑑"><MenuIcon/></Link></div><div className="report-topline"><p className="eyebrow">你的星際起源報告</p><ShareButton responses={responses} civilization={c.name}/></div><section className="result-hero"><div className="result-identity"><span className="category-tag">{c.category}</span><p className="primary-result-line">Primary · 你的主要文明</p><h1>{c.name}</h1><p className="english">{c.english}</p><p className="civ-subtitle">{shortCopy(c.lineageId)}</p><a className="button" href="#official">閱讀完整文明記憶 <ArrowRight size={17}/></a></div><div className="result-art"><Icon id={c.id}/></div></section><nav className="report-nav" aria-label="報告章節"><a href="#official">完整文明記憶</a><a href="#structure">完整排行</a>{localAttempt&&<a href="#feedback">回饋與重測</a>}<a href="#analysis">深入了解你的結果</a></nav><TopFour result={classified}/><Stability result={classified}/><OfficialText id={c.id}/>{localAttempt&&<><div className="save-status" role="status">{localAttempt.saved?<><Check size={16}/>匿名校準資料已儲存。</>:<><span>{saveState||'答案已在此裝置保存。'}</span><button className="text-button" onClick={save} disabled={saving}>{saving?'儲存中……':'重新儲存'}<RefreshCw size={14}/></button></>}</div><Feedback attempt={localAttempt}/><Retest onRestart={onRestart}/></>}<section className="report-end"><h2>每一道星光，<br/>都有值得理解的故事。</h2><div><Link className="button" to="/civilizations">探索全部 21 個文明 <ArrowUpRight size={18}/></Link><button className="text-button" onClick={onRestart}>{demo||shared.shared?'開始我的測驗':'重新測驗'} <ArrowRight size={17}/></button></div></section><section className="report-analysis" id="analysis"><p className="eyebrow">深入了解你的結果</p><div className="report-metrics"><Metric label="第一名匹配指數" value={fmt(result.public.scores[c.lineageId],1)} detail="越高，代表本次回答越接近這個文明"/><Metric label="第二名匹配指數" value={fmt(result.public.scores[result.public.runner_up.id],1)} detail="另一個值得你認識的文明"/><Metric label="結果穩定度" value={stabilityLabels[result.public.stability.label]} detail="換個角度看答案，第一名是否仍一樣"/><Metric label="已完成題目" value="60 / 60" detail={demo?'範例的完整回答':localAttempt?.imported?'來自你匯入的答案':'你的完整回答'}/></div><Ranking result={classified}/><PairComparison result={classified}/><Evidence result={classified} responses={responses}/></section><div className="report-export-bottom"><ExportButton responses={responses}/></div></div>;
}
type ClassifiedResult={public:Extract<ScoringResult['public'],{status:'classified'}>;diagnostic:Extract<ScoringResult['diagnostic'],{status:'classified'}>};
function IdentityGate({onContinue}:{onContinue:(value:{identity:string;familiarity:string})=>void}){const [known,setKnown]=useState(''),[familiarity,setFamiliarity]=useState('');const ready=Boolean(familiarity&&(known||known==='none'));return <section className="identity-gate section"><p className="eyebrow">在打開報告之前</p><h1>先留下你的直覺，<br/><em>再看看模型如何回答。</em></h1><p>你的回答會和自我認同及熟悉程度並列，方便你比較自己的感受與結果輪廓。</p><div className="identity-actions"><label>你本身對星際種子理論的熟悉程度<select value={familiarity} onChange={e=>setFamiliarity(e.target.value)}><option value="">請選擇</option><option value="none">從未接觸</option><option value="some">略有認識</option><option value="expert">專家級數</option></select></label><label>你是否有自我感覺屬於某個文明？<select value={known} onChange={e=>setKnown(e.target.value)}><option value="">請選擇</option><option value="none">沒有／不確定</option>{civs.map(c=><option value={String(c.id)} key={c.id}>{c.name}</option>)}</select></label><button className="button gold" disabled={!ready} onClick={()=>onContinue({identity:known,familiarity})}>查看我的報告 <ArrowRight size={17}/></button></div></section>}
function ShareButton({responses,civilization}:{responses:Responses;civilization:string}){
 const [open,setOpen]=useState(false),[copied,setCopied]=useState(false),[error,setError]=useState('');const closeRef=useRef<HTMLButtonElement>(null),triggerRef=useRef<HTMLButtonElement>(null),dialogRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const buttons=dialogRef.current?.querySelectorAll<HTMLButtonElement>('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',keydown);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',keydown);triggerRef.current?.focus();};},[open]);
 const url=()=>`${window.location.origin}/report?s2=${encodeResponses(responses)}`;
 const copy=async()=>{try{await navigator.clipboard.writeText(url());setCopied(true);setError('');}catch{setError('未能複製連結，請允許瀏覽器使用剪貼簿後再試。');}};
 return <><button ref={triggerRef} className="share-button" onClick={()=>{setCopied(false);setOpen(true)}}><Copy size={15}/>分享結果</button>{open&&<div className="share-modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div ref={dialogRef} className="share-modal" role="dialog" aria-modal="true" aria-labelledby="share-title"><button ref={closeRef} className="share-close" onClick={()=>setOpen(false)} aria-label="關閉分享視窗">×</button><p className="eyebrow">分享你的星際座標</p><h2 id="share-title">我的主要文明是 {civilization}。<br/><em>你的是什麼？</em></h2><p>連結包含本次完整答案，持有連結的人可以查看報告及答案。請只分享給你願意讓對方閱讀的人。</p><div className="share-actions"><button onClick={()=>window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url())}`,'_blank','noopener,noreferrer')}>Facebook</button><button onClick={()=>window.open(`https://twitter.com/intent/tweet?url=${encodeURIComponent(url())}&text=${encodeURIComponent(`我的主要文明是${civilization}。你的是什麼？`)}`,'_blank','noopener,noreferrer')}>X</button><button onClick={copy}><Copy size={15}/>{copied?'已複製連結':'複製連結'}</button></div>{error&&<p role="alert">{error}</p>}</div></div>}</>;
}
function TopFour({result}:{result:ClassifiedResult}){const near=result.diagnostic.ranking.slice(0,3),far=[...result.diagnostic.ranking].reverse().slice(0,3);const rows=(items:typeof near)=>items.map((s,i)=>{const c=civilization(s.id);return <Link className={`rank-row ${s.id===result.public.primary.id?'is-primary':''}`} to={`/civilizations/${c.id}`} key={s.id}><span className="rank-number">{String(i+1).padStart(2,'0')}</span><Icon id={c.id} size="small"/><span className="rank-name">{c.name}<small>{c.category}</small></span><div className="rank-score"><span className="score-track"><i style={{width:`${s.score}%`}}/></span><b>匹配指數 {s.score.toFixed(1)}</b></div></Link>});return <section className="top-four"><div className="top-four-columns"><div><p className="eyebrow">最匹配頭3名</p><div className="ranking-table">{rows(near)}</div></div><div><p className="eyebrow">最不匹配3名</p><div className="ranking-table">{rows(far)}</div></div></div><p className="chart-note">匹配指數越高，代表你的回答越接近這個文明。你可以同時與多個文明有共鳴；這些數字不是血統比例，也不用加起來等於 100。</p></section>}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;}
function Ranking({result}:{result:ClassifiedResult}){
 const [all,setAll]=useState(false);const rows=all?result.diagnostic.ranking:result.diagnostic.ranking.slice(0,7);
 return <section className="report-section" id="structure"><div className="section-heading"><div><p className="eyebrow">01 / 完整排行</p><h2>你的方向，如何落在星海之中。</h2></div><span className="section-note">21 個文明</span></div><p className="analysis-intro">從最接近到最不接近，看看你的回答與每個文明的相似之處。匹配指數介於 0 至 100，越高代表越接近；低分不代表好壞，只表示這些特質在本次回答中較少出現。</p><div className="ranking-table"><div className="rank-header"><span>排行 / 文明</span><span>匹配指數 0–100</span></div>{rows.map(s=>{const c=civilization(s.id);return <Link className={`rank-row ${s.id===result.public.primary.id?'is-primary':''}`} key={s.id} to={`/civilizations/${c.id}`}><span className="rank-number">{String(s.rank).padStart(2,'0')}</span><Icon id={c.id} size="small"/><span className="rank-name">{c.name}<small>{s.id===result.public.primary.id?'第一名 · 最接近你':s.id===result.public.runner_up.id?'第二名 · 同樣值得認識':c.category}</small></span><div className="rank-score"><span className="score-track"><i style={{width:`${s.score}%`}}/></span><b>匹配指數 {s.score.toFixed(1)}</b></div><ArrowUpRight className="rank-link" size={15}/></Link>;})}</div><button className="expand-button" aria-expanded={all} onClick={()=>setAll(!all)}>{all?'收合完整排行':'展開全部 21 個文明排行'} <ChevronDown size={17}/></button><p className="chart-note">每個文明分開比較，指數不需要加總為 100。50 是刻度的中間位置，不是合格線；畫面只顯示一位小數，指數看似相同時，仍可能有細微差別。</p></section>;
}
const stabilityLabels={very_high:'非常穩定',high:'穩定',moderate:'中等',low:'較不穩定',very_low:'穩定度很低',sensitive:'第一名可能改變'};
function Stability({result:r}:{result:ClassifiedResult}){
 const stability=r.public.stability,sensitive=stability.label==='sensitive';
 return <section className={`stability-panel ${sensitive?'is-sensitive':''}`} id="stability"><div className="stability-heading"><div><p className="eyebrow">STABILITY · 結果穩定度</p><h2>{stabilityLabels[stability.label]}</h2></div><div className="stability-index"><b>{fmt(stability.index,1)}</b><span>/ 100</span></div></div><p>{sensitive?'當我們調整看待答案的角度，或暫時略去一組相關答案時，有些檢查會讓另一個文明成為第一名。你的回答呈現不只一個接近的方向，可以把前幾名一起閱讀。':'即使調整看待答案的角度，或暫時略去一組相關答案，本次第一名仍然不變。穩定度也會考慮它領先其他文明多少；領先越少，方向就越需要保留彈性。'}</p><details><summary>這個數字代表什麼？ <ChevronDown size={16}/></summary><p>它回答的是：「換個角度看同一份答案，第一名還站得穩嗎？」數字越高，代表在這些檢查下，第一名越不容易改變。</p><p>我們同時看第一名領先多少、改變不同特質的重要程度後是否仍排第一，以及少看一組相關答案後是否仍排第一。只要其中一項較弱，穩定度就會降低。</p><p className="chart-note">這是同一份答案的結構穩定度，不是你「有多像」某個文明，也不是結果正確的機率。它不能保證你下次測驗會得到同樣結果。</p></details></section>;
}
function AnswerText({question:q,answer:a}:{question:Question;answer:Answer}){
 if(q.format==='BIP'&&typeof a==='number')return <><p><b>你的回答：</b>{a===4?'兩者相當':`${a<4?'偏向左側':'偏向右側'}（${a} / 7）`}</p><p><span>左側</span> {q.left}</p><p><span>右側</span> {q.right}</p></>;
 if(q.format==='BWS'&&typeof a==='object'&&'best' in a)return <><p><b>最像自己：</b>{q.options[a.best]}</p><p><b>最不像自己：</b>{q.options[a.worst]}</p></>;
 if(q.format==='CROSS'&&typeof a==='object'&&'operation' in a)return <><p><b>{q.operation_prompt}</b><br/>{q.operations[a.operation]}</p><p><b>{q.goal_prompt}</b><br/>{q.goals[a.goal]}</p></>;
 return null;
}
function Evidence({result:r,responses}:{result:ClassifiedResult;responses:Responses}){
 const [view,setView]=useState<'impact'|'all'>('impact'),entries=r.diagnostic.item_contributions;
 const ordered=view==='all'?entries:[...entries].sort((a,b)=>Math.abs(b.winner_over_runner_t_points)-Math.abs(a.winner_over_runner_t_points)).slice(0,8);
 const p=civilization(r.public.primary.id),runner=civilization(r.public.runner_up.id);
 return <section className="report-section" id="evidence"><div className="section-heading"><div><p className="eyebrow">03 / 回看你的答案</p><h2>哪些選擇，讓你更接近它們？</h2></div><div className="segmented"><button className={view==='impact'?'active':''} onClick={()=>setView('impact')} aria-pressed={view==='impact'}>關鍵 8 題</button><button className={view==='all'?'active':''} onClick={()=>setView('all')} aria-pressed={view==='all'}>全部 60 題</button></div></div><p className="analysis-intro">以下比較「{p.name}」與「{runner.name}」。先看看對兩者差別影響較大的 8 道回答，你也可以展開全部答案。單一道選擇不會決定你屬於哪個文明。</p><div className="evidence-list">{ordered.map(item=>{
 const index=questions.findIndex(q=>q.id===item.id),q=questions[index],value=item.winner_over_runner_t_points;
 const closer=value>0?p.name:runner.name;
 return <details className="evidence-row" key={item.id}><summary><span className="evidence-q">Q{String(index+1).padStart(2,'0')}</span><span className="evidence-stem">{q.stem}</span><span className={`answer-direction ${value<0?'toward-runner':''}`}>{value===0?'兩者相當':`偏向${closer}`}</span><ChevronDown size={16}/></summary><div className="evidence-detail"><AnswerText question={q} answer={responses[q.id]}/><p className="chart-note">{value===0?'這道回答沒有讓其中一個文明更領先。':`只比較這兩個文明時，這道回答讓「${closer}」更佔優勢。最後的排行仍取決於整份答案。`}</p></div></details>;
 })}</div></section>;
}
function Feedback({attempt}:{attempt:Attempt}){const [fit,setFit]=useState(0),[self,setSelf]=useState(''),[prior,setPrior]=useState('unsure'),[priorId,setPriorId]=useState(''),[comment,setComment]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const response=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({attemptId:attempt.attemptId,feedbackToken:attempt.feedbackToken,fit,selfLineage:self?Number(self):null,priorIdentity:prior,priorLineage:prior==='yes'&&priorId?Number(priorId):null,comment})});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||"暫時無法儲存回饋。");setStatus('回饋已儲存。謝謝你讓這份星圖更加清晰。');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
 const options=<><option value="">不確定</option>{civs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</>;
 return <section className="feedback-section report-section" id="feedback"><div><p className="eyebrow">讓你的聲音，回到星圖之中</p><h2>這份記憶，<br/>與你有多靠近？</h2><p>分享你的真實感受，協助未來的模型校準。回饋自由填寫，不影響本次結果。</p><Link className="text-button" to="/privacy">匿名資料如何使用 <ArrowUpRight size={16}/></Link></div><form onSubmit={submit}><fieldset><legend>結果符合程度</legend><div className="fit-scale">{[1,2,3,4,5,6,7].map(v=><label key={v} className={fit===v?'selected':''}><input required type="radio" name="fit" value={v} checked={fit===v} onChange={()=>setFit(v)}/><span>{v}</span></label>)}</div><div className="scale-labels"><span>很不符合</span><span>非常符合</span></div></fieldset><label>最符合／最不像自己的地方 <span>（選填）</span><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={2000} rows={4} placeholder="說說讓你有感的片段。請勿填寫姓名、聯絡方式等個人資料。"/></label><small>{comment.length} / 2000</small><button className="button gold" type="submit" disabled={busy||!attempt.saved}>{busy?'正在儲存……':'送出匿名回饋'}<ArrowRight size={17}/></button>{!attempt.saved&&<p className="chart-note">完成答案儲存後即可提交回饋，請使用上方「重新儲存」。</p>}<p className="form-status" role="status">{status}</p></form></section>;}
function Retest({onRestart}:{onRestart:()=>void}){const [code]=useState(participant),[copied,setCopied]=useState(false);return <section className="retest panel"><div><p className="eyebrow">留一個座標，給未來的你</p><h3>匿名重測碼</h3><p>此裝置會自動連結未來測驗。換裝置時，可在「資料與隱私」輸入這組代碼，延續匿名重測紀錄。</p></div><div><code>{code}</code><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(code);setCopied(true);}catch{setCopied(false);}}}><Copy size={15}/>{copied?'已複製':'複製代碼'}</button><button className="text-button" onClick={onRestart}>開始一次新的測驗 <ArrowRight size={15}/></button></div></section>;}
export function Privacy(){useTitle('資料與隱私');const [code,setCode]=useState(''),[status,setStatus]=useState('');function restore(e:FormEvent){e.preventDefault();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(code.trim()))return setStatus('請輸入完整的匿名重測碼。');if(write('starseed2-participant',code.trim().toLowerCase()))setStatus('匿名重測碼已設定，下一次完成的測驗將連結至這組代碼。');else setStatus('此瀏覽器無法保存代碼，請允許本機儲存後再試。');}
 return <div className="privacy-page section"><p className="eyebrow">資料與隱私</p><h1>讓記憶留下，<br/><em>讓身份保持匿名。</em></h1><div className="privacy-prose"><h2>完成測驗時會保存什麼</h2><p>完成 60 題後，網站會自動提交匿名校準資料：隨機產生的參與者與測驗識別碼、60 題的原始答案、模型版本、開始與完成時間、作答時長、匯入狀態、由伺服器計算的結果、21 個完整精度分數、結構穩定度及邊界指標，以及網站與部署版本。若沒有足夠方向資訊，則保留「未分類」狀態。</p><p>未完成的測驗只留在你的瀏覽器，不會寫入校準資料庫。報告範例與分享報告會將答案傳送至伺服器計算，但不寫入匿名校準資料庫。匯入答案會重新計算，並以匯入紀錄保存；其作答時長記為匯入處理時間。</p><h2>資料用來做什麼</h2><p>分析題目表現、分類邊界、匿名重測一致性與自我認同回饋，協助未來研究和建立明確的新模型版本。目前凍結的題目、權重、計分與分類不會因收集資料而自動改變。紀錄保留供歷史結果重建與校準研究使用。</p><h2>自由填寫的結果回饋</h2><p>結果符合程度與選填文字，只在你主動送出回饋時保存。請勿在文字回饋中填入姓名、電話、email 或其他身份資料。</p><h2>身份與基礎設施</h2><p>網站不要求帳號，不收集姓名、電話、email、精確位置、完整地址、裝置指紋或廣告識別碼，也不使用第三方廣告追蹤器。匿名重測碼用於連結你的多次測驗，不提供公開查詢個人答案的功能，請自行保管。</p><p>網站與資料庫由 Cloudflare Workers 與 D1 承載。Cloudflare 為提供網路服務與防濫用會處理必要的連線資訊；應用程式不把 IP 位址或瀏覽器指紋寫入校準資料庫。資料沒有公開下載介面。</p><h2>分享報告</h2><p>分享連結包含完整答案及測驗版本，不包含匿名重測碼或回饋驗證碼。任何持有連結的人都可以重新計算報告、查看及匯出答案。開啟分享報告不會取代此裝置的個人結果。</p><h2>這個裝置上的資料</h2><p>瀏覽器本機儲存包含未完成進度、最近一次完成的答案與報告、匿名參與者識別碼及回饋驗證碼。你可隨時匯出完整答案，也可透過瀏覽器清除此網站的本機資料；清除本機資料不會刪除已提交的匿名校準紀錄。</p><h2>換裝置後延續重測</h2><p>輸入之前保存的匿名重測碼。設定只影響之後完成的測驗，不會變更既有紀錄。</p><form className="restore-form" onSubmit={restore}><label>匿名重測碼<input type="text" value={code} onChange={e=>setCode(e.target.value)} placeholder="xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx" autoComplete="off" maxLength={36}/></label><button className="button" type="submit">設定重測碼</button><p role="status">{status}</p></form><Link className="text-button" to="/quiz">返回你的旅程 <ArrowRight size={16}/></Link></div></div>;
}
